- name: Configurar Docker e Zabbix Agent

  vars:
    zabbix_agent_server: "127.0.0.1"
    zabbix_agent_serveractive: "127.0.0.1"
    zabbix_agent_version: "6.0"
    zabbix_agent_package_state: present

  hosts: all
  become: true
  roles:
    - geerlingguy.docker
    - role: zabbix.agent
