---
# Playbook 1 - Docker via Role
- name: Instalação Docker via Role
  hosts: all
  remote_user: ubuntu
  become: true
  tags: docker

  vars:
    docker_install_compose: true

  roles:
    - geerlingguy.docker

# Playbook 2 - Zabbix
- name: Instalação Zabbix Agent 6
  hosts: all
  become: true
  tasks:
    - name: Baixar e adicionar chave GPG do Zabbix
      ansible.builtin.apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present

    - name: Adicionar repositório do Zabbix
      ansible.builtin.apt_repository:
        repo: "deb https://repo.zabbix.com/zabbix/6.0/ubuntu {{ ansible_distribution_release }} main"
        state: present
        filename: zabbix
        update_cache: yes

    - name: Instalar Zabbix Agent
      ansible.builtin.apt:
        name: zabbix-agent
        state: present
        update_cache: yes
