steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup packer
    uses: hashicorp/setup-packer@v1

  - name: Criar arquivo da chave privada
    run: |
      echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > packer/ansible-key.pem
      chmod 600 packer/ansible-key.pem

  - name: Packer init
    run: packer init packer/

  - name: Packer validate
    run: packer validate packer/
