name: packer validation

on:
  pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write private key file
        run: |
          mkdir -p packer
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > packer/ansible-key.pem
          chmod 600 packer/ansible-key.pem

      - name: Setup Packer
        uses: hashicorp/setup-packer@v1
        with:
          version: latest

      - name: Run packer init
        run: packer init packer/

      - name: Run packer validate
        run: packer validate packer/
