name: packer validation

on:
  pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Run packer init
        run: packer init .

      - name: Run packer validate
        run: packer validate .
